### ISSUE TITLE
Use Excalidraw instead of Figma

### ISSUE THREAD

**Issue by aitchkhan** [ehsaantech/book-app#1]
In the design section, instead of using Figma, my suggestion is to use Excalidraw. Reason being, the figma is not a book-design figma. Second reason, we can only do wireframes on Excalidraw. It will bring the creativity out of an engineer.

https://github.com/ehsaantech/book-app?tab=readme-ov-file#design

@m-hassan-97 @Tanzeel-khan 

Happy to discuss it further.

**Comment by Tanzeel-khan** [comment]
Thanks for sharing your suggestion. I would like to discuss it further with
you.
